### ISSUE TITLE
缺少配置文件目录

### ISSUE THREAD

**Issue by java-war** [chaokunyang/microservices-event-sourcing#3]
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaokunyang/spring-event-sourcing.git
        searchPaths: config-repository

**Comment by chaokunyang** [comment]
你好，配置文件目录已添加。目前添加了online-store-app的dev、test、prod配置文件示例。由于在test、prod环境的配置与具体环境紧密相关，所以项目只给了配置方式，具体使用需结合实际应用环境。注意一点，在默认配置下，服务在配置服务器中的配置不会被本地应用的配置覆盖。
