### ISSUE TITLE
请教：每个模块下面都有相同的entity bean

### ISSUE THREAD

**Issue by toeasy** [chaokunyang/microservices-event-sourcing#4]
初看了代码，发现每个模块下都有相同的实体类 Account Address...
能有什么方式可以共享实体类，或者更优雅的模式？

**Comment by chaokunyang** [comment]
不建议在微服务中复用/共享这类代码，会引起服务间的耦合。重复是更好的选择。

**Comment by chaokunyang** [comment]
不要让业务逻辑泛化。业务逻辑是面向领域建模的，复用会导致业务逻辑变得模糊、失去表达性，增加技术债。而且增大改变成本，而微服务要做的一件事就是快速进化。
代码复用不总是好的。

**Comment by toeasy** [comment]
确实在这微服务场景下复用可能引起实体边界不清晰，但也有另一方面，如果有实体需做修改调整，在多模块中都存在，是不是只能逐个修改啦

**Comment by chaokunyang** [comment]
实际使用时是每个服务一个代码库，而不是多模块构建。微服务需要独立进化，如果共享实体库，会引起耦合，无法独立进化，发布。
